### ISSUE TITLE
Unmatched time, hourly buzz issues

### ISSUE THREAD

**Issue by ysy5700** [cozie-app/cozie#116]
Hello Pierre and @mariofrei, 

I've sent the support request on Slack since I couldn't get the valid dataset from the newly updated questionnaires on Fitbit.

The problem that I confronted are as follows:

- Unmatched timezone: in [Kaggle](https://www.kaggle.com/seoyeonyun/hobel-data-retrieve/edit), the timezone is set as Asia/Singapore -- can we change it to my time zone (Europe/Switzerland)? GMT+2
- API -- Do I need to set up a new API to get my data response?
- Limited data responses: I built new 16 questions but after finishing the feedback, I can only see 3 responses from 3 questions. -- how I can fix this to get the full response?
- Buzz time: hourly buzz setup in OS simulator doesn't seem to work - Is any other solution for this? 

Thanks and I look forward to your quick support :) 

Best wishes,
Seoyeon

**Comment by mariofrei** [comment]
Hi Seoyeon,

**Timezone**
You probably want to use 'Etc/GMT+2'instead of 'Asia/Singapore'. 
You can get a list of all available timezones with the following bit of python code:
```
import pytz
 
for tz in pytz.all_timezones:
  print(tz)
```

**API & Limited data responses**
There shouldn't be a need for a new API. 
Could you provide the file with new questions? 
I will then check in the database if there is something similar there.

**Buzz time **
I think that has never properly worked on the Versa 2. 
@Pierre do you have time to look into this issue?

**Comment by ysy5700** [comment]
Thanks @mariofrei. 
Indeed, the time is not matching after changing to Etc/GMT+2. It shows 6-7 am instead of 14 pm. (below image)
![image](https://user-images.githubusercontent.com/61016546/164014895-071dc897-0ace-44c0-8168-71805593e589.png)

Here I attached the new question file (in the folder of resources>flows>activity-flows.js)
Please have a look and let me know why the kaggle doesn't show all responses. 
-------------
[activity-flow.txt](https://github.com/cozie-app/cozie/files/8513429/activity-flow.txt)
-------------

And plus, I've noticed that I cannot publish the app.fba file on the https://gam.fitbit.com/
It shows that app ID already exists. Do you think I need to change the file name? (In this case, I need to change some other lines in the cozie folder right?) 

Thanks for helping me.

**Comment by mariofrei** [comment]
I could find all answers from your question flow file (activity-flow.txt) plus the response to a question named posture.
I think you switched `experimentid` and `userid`, 
The following line works for me:

```
payload = {'experiment-id': 'hobel02', 'weeks': '30', 'user-id': 'hobel'}
```

I'd suggest to use "hobel02" as `userid` and "hobel" as `experimentid` in the future.

**Comment by ysy5700** [comment]
Thanks Mario, Limited data responses/Timezone issues are solved now. 

However, I can actually see that package.json file shows the right App ID: 1ef995a9-ca67-4e76-b2c4-5d650a644c97
![image](https://user-images.githubusercontent.com/61016546/164043964-38c7cc52-4421-47bc-bd0d-7846be83c36a.png)

But I cannot publish it in the https://gam.fitbit.com it says "app id already in use". 
This publishing is that I have 3 extra fitbit watches which I would like to use the same clockface (that I created). 
![image](https://user-images.githubusercontent.com/61016546/164045010-b77c7f1d-67c4-46df-a2c5-5be482a44eea.png)


Do you have any other solutions? 
I've logged into gam.fitbit.com with the userID/PW same as on the paired fitbit.

**Comment by ysy5700** [comment]
Hello @mariofrei I think I found the issues 
When I find my App UUID in the fitbit gallery I can see this is already used by Federico. 
https://gallery.fitbit.com/details/1ef995a9-ca67-4e76-b2c4-5d650a644c97

How I can publish my own app UUID?

**Comment by ThePebblesFr** [comment]
Hi Seoyeon,

**Buzz Time**
I believe that this feature has not been working on any version of the code, I am working on it.

**Comment by mariofrei** [comment]
Hi Seoyeon,
When you create a new clockface on gam.fitbit.com a new ID should be assigned. That's _your_ ID. You need to take that ID and copy it into your package.json file. The ID that is currently in the package.json file is there because Federico did the same  before for _his_ clockface.

**Comment by ThePebblesFr** [comment]
I fixed the issue with the **Buzz Time** and pushed it to the cozie-researcher branch.

Seoyeon, if you need help to get the version without buzzer issue, let me know.

**Comment by ysy5700** [comment]
@ThePebblesFr Thanks Pierre, could you help me to apply the buzz time from cozie-researcher to HOBEL branch? Which file that I need to patch? Could you give the step-by-step instruction on that? I don't want to erase essential files on my branch. 

My branch is named as "HOBEL", you're welcomed to have a look. Thanks,

**Comment by ysy5700** [comment]
@mariofrei 
Do you think the developer ID is the new ID that I'm assigned? Actually I don't have the same webpage like PJ had on the youtube. (https://youtu.be/5JaCrZBZbt0?t=91) 
![image](https://user-images.githubusercontent.com/61016546/164164310-2dd00797-9008-4e36-93f3-685a2c1a5b28.png)

If this developer ID is the one that I need to copy/paste into the package.json file, I do it after your checking. Thanks!

**Comment by mariofrei** [comment]
I think the developer ID is the new ID assigned to the clockface. 
At least according to this: https://community.fitbit.com/t5/SDK-Development/Invalid-UUID/td-p/4319171

**Comment by ThePebblesFr** [comment]
Would you be able to give me the link of your branch? Because, tell me if I am wrong, but there is no branch named "HOBEL" on this repo.

By the way, to fix the buzzer issues, I think that the only part of the code you have to change is in the **index.js** file, in the **BUZZER SELECTOR** part of the code. The **setInterval** function must be like this:

`const currentDate = new Date(); // get today's date
    const currentDay = currentDate.getDay(); // get today's day
    const currentHour = currentDate.getHours();

    console.log("starting to evaluate whether the watch need to vibrate or not");

    try {
        const buzzSelection = parseInt(fs.readFileSync("buzzSelection.txt", "json").buzzSelection); // read user selection
        vibrationTimeArray = buzzOptions[buzzSelection];
    } catch (e) {
        console.log("Could not open the file buzzSelection.txt");
        console.log(e);
        if (!isProduction) {
            bodyErrorLabel.text = bodyErrorLabel.text + "Vibration : " + e;
        }
    }

    if (currentDay !== startDay) { // if it is a new day check user
        startDay = currentDay;
        completedVibrationCycleDay = false;
    }

    if (vibrationTimeArray.length != 0) {
        const maxHour = vibrationTimeArray.reduce(function(a, b) {
            return Math.max(a, b);
        });
    } else {
        const maxHour = 0
    }


    if (!completedVibrationCycleDay) {
        // Ensure that the next vibration isn't passed
        let i = 0;
        while (vibrationTimeArray[i] <= currentHour)
        {
            const firstElement = vibrationTimeArray.shift();
            vibrationTimeArray.push(firstElement);
            i++;
        }
        if (i != vibrationTimeArray.length)
        {
            console.log("Next hour of vibration : " + vibrationTimeArray[0]);
            if (vibrationTimeArray[0] === currentHour && bodyPresence.present && getView() === 0) { // REMOVED : && today.adjusted.steps > 300 -- vibrate only if the time is right and the user has walked at least 300 steps and the watch is worn
                // this ensures that the watch does not vibrate if the user is still sleeping
                console.log("The watch should vibrate");
                vibrate();
                const firstElement = vibrationTimeArray.shift();
                vibrationTimeArray.push(firstElement);
                if (currentHour === maxHour) {
                    completedVibrationCycleDay = true;
                }
            } else if (vibrationTimeArray[0] < currentHour) { // the vector is shifted by one since the that hour is already passed
                const firstElement = vibrationTimeArray.shift();
                vibrationTimeArray.push(firstElement);
            }
        }
    }`
    
    Let me know if it worked.

**Comment by ysy5700** [comment]
@mariofrei I fixed it! you were right. :) 
Here if you would like to see my app branch : https://gallery.fitbit.com/details/a914a8ca-4529-42b4-9a6d-ee054ce6653b

@ThePebblesFr  I will work on this today afternoon. And ping you again

**Comment by ThePebblesFr** [comment]
@ysy5700, i updated the **activity-flow.js** file that you send before so that it fits the latest version of the code -->
[activity-flow.txt](https://github.com/cozie-app/cozie/files/8520348/activity-flow.txt)

Apparently, if you follow the steps below, you might be able to run your question flow without any bug, and you might also be able to add 4-answers questions and buzzer:

- create an empty folder
- clone the branch cozie-researcher: git clone -b cozie-researcher https://github.com/cozie-app/cozie.git
- add your flow to the flows folder (make sure the extension of this file is .js
- add your icons
- in index.js, change the 45th line by this : `import totalFlow from "../resources/flows/activity-flow";`
- build and install

If something doesn't work, please let me know.

**Comment by ysy5700** [comment]
@ThePebblesFr Hello Pierre, I git clone the cozie-researcher in one empty-folder (seoyeone) but I cannot see the "flow" folder. So I couldn't proceed the further steps. 
![image](https://user-images.githubusercontent.com/61016546/164237462-e2255a86-31e9-48da-ba24-73a667a1a2a5.png)


Here is my github [**https://github.com/ysy5700/cozie**](https://github.com/ysy5700/cozie/tree/HOBEL)
Could you fix the buzz issues directly? How I can share with you my github for editing?
Thanks!

**Comment by ThePebblesFr** [comment]
You forgot the “-b cozie-researcher” to clone the right branch:

git clone -b cozie-researcher https://github.com/cozie-app/cozie.git

**Comment by ThePebblesFr** [comment]
Yes, that’s it!

**Comment by ysy5700** [comment]
@ThePebblesFr 
What does it mean by API can be different? How I can check and where I can change? which file?

**Comment by ThePebblesFr** [comment]
Yes, sometimes it is fail. You should disconnect/reconnect your fitbit account. On my computer, it has always been solving the issues.

**Comment by ysy5700** [comment]
Do you think the device(watch) should have strong wifi to be connected?

**Comment by ThePebblesFr** [comment]
Did you disconnect/reconnect your fitbit os simulator?

**Comment by ysy5700** [comment]
yeap both of them

**Comment by ysy5700** [comment]
Now I did again to log-out and log-in in OS simulator it got stuck like this. 
![image](https://user-images.githubusercontent.com/61016546/164250187-b42b52d8-7b06-4b0f-a20e-49a57a96d202.png)

**Comment by ThePebblesFr** [comment]
Do you have TeamViewer? I could try to fix it. I don't really know what is wrong..

**Comment by ysy5700** [comment]
yeap thanks here is my ID/PW
ID: 366 354 330
PW: y5ngtd1d

**Comment by ysy5700** [comment]
https://epfl.zoom.us/j/66340908872

The zoom is ready as well

**Comment by ysy5700** [comment]
Are you still there?

**Comment by ysy5700** [comment]
Hello @ThePebblesFr, 
Today I'm wearting the fitbit watch but there's no buzz going on every hour (there was nothing at least once..) 

And I found out that the touch button (left circle when there is only two option: e.g. standing / sitting) is not working after we change the code yesterday. 

Could you look at the scripts again if there's a problem? 
In that case, I may use the code that I've constructed before.

Thanks!

**Comment by ThePebblesFr** [comment]
I found out a bug with these buttons too. I fixed it and pushed it on `cozie-researcher` branch.

For the buzzer, we will figure it out during our zoom call.

**Comment by pedramnojedehi** [comment]
> @mariofrei Do you think the developer ID is the new ID that I'm assigned? Actually I don't have the same webpage like PJ had on the youtube. (https://youtu.be/5JaCrZBZbt0?t=91) ![image](https://user-images.githubusercontent.com/61016546/164164310-2dd00797-9008-4e36-93f3-685a2c1a5b28.png)
> 
> If this developer ID is the one that I need to copy/paste into the package.json file, I do it after your checking. Thanks!

I know you have managed to fix the issue related to "appUUID" but I'm just writing the effective solution here for the record:

1. Rename your package.json to package.json.txt
2. Delete the line with the AppUUID
3. Rename package.json.txt to package.json
4. Type the following on the terminal: npx fitbit-build generate-appid
5. Then, a new app ID will be written, and you can re-build and install the app.
6. Then by using the new fba file generated you can try publishing again.

if there is a better way of resolving this, please let me know.

**Comment by mariofrei** [comment]
@ThePebblesFr could you respond to the question above?

**Comment by ThePebblesFr** [comment]
I tried your solution @pedramnojedehi. I don't understand how it can work because the app UUID must match the Developer ID of your Fitbit account, otherwise you can't upload any .fba file in the fitbit gallery. Hence, the appUUID field in the package.json file can't be generated.

**Comment by ThePebblesFr** [comment]
Unless you found a way to change this Developer ID to the appUUID generated, I'm not sure it can work.
<img width="296" alt="image" src="https://user-images.githubusercontent.com/89025765/177914463-0995631d-2984-4a49-a268-45602a10cca9.png">
Here is the developer ID I'm talking about for one of our fitbit acount.

**Comment by pedramnojedehi** [comment]
> I tried your solution @pedramnojedehi. I don't understand how it can work because the app UUID must match the Developer ID of your Fitbit account, otherwise you can't upload any .fba file in the fitbit gallery. Hence, the appUUID field in the package.json file can't be generated this way.

@ThePebblesFr: I'm seeing things differently on my end:
First version:
![image](https://user-images.githubusercontent.com/55299610/177916618-bfe0f0b0-c779-4461-b4fc-a3918d57911e.png)
Second version:
![image](https://user-images.githubusercontent.com/55299610/177916826-099a4951-7178-4fc7-872c-104ad15c6f04.png)
As you can see appUUID could vary according to your app but your developer ID is fixed. There might better solutions but I tested this solution a few times and that worked every time.

**Comment by ThePebblesFr** [comment]
So, if I understood correctly, you published a version of your app with a first appUUID and then you generated a new UUID and built the app again. Then, when you publish the new version with the new appUUID, it works?

**Comment by pedramnojedehi** [comment]
Basically, you cannot publish an app whose appUUID was already published. You would face an error and are not able to publish anything. So, I  could never publish my own version because you guys published "Cozie for researcher" app once earlier with that specific appUUID. So, I went through my solution, then I got a new appUUID and upload a new .fba file on Fitbit gallery.
And the explanation of the screenshots above: I went through the solution twice to show that we can create different appUUID over and over again and they can be uploaded without any problem while everything is identical in these apps.

**Comment by ThePebblesFr** [comment]
Ok I finally managed to do so. A few weeks ago, I tried so many times to do that and it has never worked. Now it works! Thanks a lot.
By the way, I'm not sure that you need to do the 1st and 3rd steps (rename package.json to a txt file). You can simply open the package.json file and remove the appUUID line (and the comma above) and it works.

**Comment by pedramnojedehi** [comment]
Yes, agreed! I skipped those steps later and yet that worked. 
And yes, "(and the comma above)" must be erased, that's the catch :D
